image: humancellatlas/metrics-build-box:latest

variables:
  ## variables for the build
  AWS_DEFAULT_REGION: us-east-1
  ELASTICSEARCH_DOMAIN: hca-logs
  ## variables for docker
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://localhost:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

services:
- docker:18.09-dind

stages:
- image
- deploy

before_script:
  - export IMAGE_TAG=${CI_BUILD_REF_NAME}-$(git describe --tags --always)-${CI_PIPELINE_ID}
  - export CICD_ROLE="arn:aws:iam::$(aws sts get-caller-identity | jq -r .Account):role/$(aws sts get-caller-identity | jq -r .Arn | cut -d/ -f2)"
  - eval "$(aws ecr get-login --no-include-email)"
  - ./await_active_port.sh 2375

build_publish:
  stage: image
  script:
    - make init target image publish

deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - make init deploy
